import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class SeedService {
  private readonly logger = new Logger(SeedService.name);

  constructor(private readonly prisma: PrismaService) {}

  async seed() {
    const count = await this.prisma.ticket.count();
    if (count > 0) {
      this.logger.log(`Ya existen ${count} tickets. Saltando seed.`);
      return;
    }

    this.logger.log('Sembrando tickets de ejemplo...');

    const tickets = [
      {
        title: 'No puedo ingresar al SIIU',
        description: 'Hola, soy estudiante de la Facultad de Ciencias Exactas. Desde ayer no puedo ingresar al SIIU con mi usuario y contraseña. Me sale "usuario no encontrado". Necesito revisar mis notas.',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Inconvenientes en el ingreso',
        tipo_solicitud: 'INCIDENTE',
        priority: 'alto',
        urgency: 'alto',
        impact: 'medio',
        status: 'ABIERTO',
        requester: 'Carlos Pérez',
        tipo_usuario: 'ESTUDIANTE',
        facultad_o_area: 'Ciencias Exactas',
        carrera: 'Sistemas de la Información',
        ai_suggestion: '**PROCEDIMIENTO** | 1) Verificar credenciales en SIIU. 2) Revisar estado de cuenta. 3) Contactar a secretaría. | **ESCALAMIENTO** | Si no se resuelve en 24h, escalar a DTIC. | **REFERENCIA** | KB-SIIU-001',
        user_recommendation: '**QUE HACER** | Intenta recuperar tu contraseña desde la página de inicio del SIIU. | **DONDE ACUDIR** | Secretaría de tu facultad. | **DOCUMENTOS** | Cédula de identidad.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N1 -> N2 si persiste | **PRIORIDAD COBIT** | DSS02.03 | **ACCIONES DE MEJORA** | Verificar logs de autenticación',
        itil_category: 'Gestión de Incidentes',
        cobit_control: 'DSS02.03',
        cost_human: 15.0,
        cost_ia: 0.05,
      },
      {
        title: 'Problemas con acceso a UVirtual',
        description: 'Docente de la Facultad de Filosofía. No puedo acceder al aula virtual UVirtual para subir los materiales de mi clase. Me sale error 503 al cargar la página.',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Inconvenientes en el ingreso',
        tipo_solicitud: 'INCIDENTE',
        priority: 'critico',
        urgency: 'urgente',
        impact: 'alto',
        status: 'EN_PROGRESO',
        requester: 'María Gómez',
        tipo_usuario: 'DOCENTE',
        facultad_o_area: 'Filosofía',
        carrera: null,
        ai_suggestion: '**PROCEDIMIENTO** | 1) Verificar estado del servidor UVirtual. 2) Limpiar caché del navegador. 3) Probar con otro navegador. | **ESCALAMIENTO** | Error 503 indica problema de servidor, escalar a DTIC inmediatamente. | **REFERENCIA** | KB-UVirtual-002',
        user_recommendation: '**QUE HACER** | Limpia la caché de tu navegador e intenta con Chrome o Edge. | **DONDE ACUDIR** | campusvirtual@uce.edu.ec | **DOCUMENTOS** | Captura de pantalla del error.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N2 - DTIC | **PRIORIDAD COBIT** | DSS02.04 | **ACCIONES DE MEJORA** | Monitorear disponibilidad de UVirtual',
        itil_category: 'Gestión de Incidentes',
        cobit_control: 'DSS02.04',
        cost_human: 45.0,
        cost_ia: 0.05,
      },
      {
        title: 'Solicitud de certificado de notas',
        description: 'Buenos días, necesito un certificado de notas para mi postulación a una beca. Ya realicé el trámite en secretaría pero no encuentro cómo descargarlo desde el SIIU.',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Certificados para posgrado/externas',
        tipo_solicitud: 'SOLICITUD_SERVICIO',
        priority: 'medio',
        urgency: 'medio',
        impact: 'bajo',
        status: 'RESUELTO',
        requester: 'Ana López',
        tipo_usuario: 'ESTUDIANTE',
        facultad_o_area: 'Ciencias Médicas',
        carrera: 'Medicina',
        ai_suggestion: '**PROCEDIMIENTO** | 1) Ingresar al SIIU. 2) Ir a Reportes > Certificados. 3) Seleccionar tipo de certificado. 4) Descargar PDF. | **ESCALAMIENTO** | Si no aparece la opción, contactar a secretaría. | **REFERENCIA** | KB-SIIU-003',
        user_recommendation: '**QUE HACER** | Ingresa al SIIU, ve a la sección Reportes y selecciona Certificados. | **DONDE ACUDIR** | Secretaría de tu facultad si no aparece la opción. | **DOCUMENTOS** | Ninguno.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N1 | **PRIORIDAD COBIT** | DSS02.01 | **ACCIONES DE MEJORA** | Actualizar guía de usuario SIIU',
        itil_category: 'Gestión de Solicitudes de Servicio',
        cobit_control: 'DSS02.01',
        resolution_time_minutes: 120,
        cost_human: 30.0,
        cost_ia: 0.05,
      },
      {
        title: 'Correo institucional no envía mensajes',
        description: 'Mi correo @uce.edu.ec no envía mensajes desde ayer. Los correos se quedan en la bandeja de salida. Ya probé en Outlook web y desktop. Soy personal administrativo.',
        category: 'SOPORTE_TECNICO_A_USUARIOS',
        subcategoria: 'Inconvenientes en envío y recepción',
        tipo_solicitud: 'INCIDENTE',
        priority: 'alto',
        urgency: 'alto',
        impact: 'alto',
        status: 'ABIERTO',
        requester: 'Pedro Martínez',
        tipo_usuario: 'ADMINISTRATIVO',
        facultad_o_area: 'Rectorado',
        carrera: null,
        ai_suggestion: '**PROCEDIMIENTO** | 1) Verificar configuración SMTP. 2) Revisar cuota de almacenamiento. 3) Verificar si hay bloqueo por 2FA. | **ESCALAMIENTO** | Si afecta a varios usuarios, escalar a DTIC como incidente masivo. | **REFERENCIA** | KB-Correo-001',
        user_recommendation: '**QUE HACER** | Revisa tu cuota de almacenamiento en Outlook Web. Si está llena, elimina correos antiguos. | **DONDE ACUDIR** | Departamento informático de tu facultad. | **DOCUMENTOS** | Captura del error.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N1 -> N2 | **PRIORIDAD COBIT** | DSS02.04 | **ACCIONES DE MEJORA** | Verificar estado del servidor Exchange',
        itil_category: 'Gestión de Incidentes',
        cobit_control: 'DSS02.04',
        cost_human: 20.0,
        cost_ia: 0.05,
      },
      {
        title: 'Duda sobre proceso de titulación',
        description: 'Estoy en mi último semestre y quiero conocer los pasos para el proceso de titulación. ¿Qué documentos necesito? ¿Dónde presento la solicitud?',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Guía del proceso',
        tipo_solicitud: 'SOLICITUD_SERVICIO',
        priority: 'medio',
        urgency: 'bajo',
        impact: 'bajo',
        status: 'CERRADO',
        requester: 'Laura Sánchez',
        tipo_usuario: 'ESTUDIANTE',
        facultad_o_area: 'Jurisprudencia',
        carrera: 'Derecho',
        ai_suggestion: '**PROCEDIMIENTO** | 1) Revisar guía de titulación en la página web UCE. 2) Acercarse a la unidad de titulación de su facultad. 3) Presentar documentos requeridos. | **ESCALAMIENTO** | Consultas complejas derivar a Coordinación de Titulación. | **REFERENCIA** | KB-Titulacion-001',
        user_recommendation: '**QUE HACER** | Revisa la guía de titulación en la página web de la UCE. | **DONDE ACUDIR** | Unidad de Titulación de tu facultad. | **DOCUMENTOS** | Cédula, certificado de notas, plan de titulación.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N1 | **PRIORIDAD COBIT** | DSS02.01 | **ACCIONES DE MEJORA** | Mantener guías actualizadas en la web',
        itil_category: 'Gestión de Solicitudes de Servicio',
        cobit_control: 'DSS02.01',
        resolution_time_minutes: 45,
        cost_human: 11.25,
        cost_ia: 0.05,
      },
      {
        title: 'Problema con acceso peatonal - torniquete',
        description: 'El torniquete de la entrada principal de la Facultad de Ingeniería no funciona desde esta mañana. Los estudiantes no pueden ingresar. Ya reporté a seguridad pero no han solucionado.',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Inconvenientes con el acceso',
        tipo_solicitud: 'INCIDENTE',
        priority: 'critico',
        urgency: 'urgente',
        impact: 'alto',
        status: 'EN_PROGRESO',
        requester: 'Juan Rodríguez',
        tipo_usuario: 'DOCENTE',
        facultad_o_area: 'Ingeniería',
        carrera: null,
        ai_suggestion: '**PROCEDIMIENTO** | 1) Contactar a la unidad de seguridad. 2) Verificar sistema de control de accesos. 3) Activar plan de contingencia (entrada manual). | **ESCALAMIENTO** | Si no se resuelve en 2h, escalar a DTIC como incidente crítico. | **REFERENCIA** | KB-Accesos-001',
        user_recommendation: '**QUE HACER** | Usa las entradas alternativas habilitadas mientras se repara el sistema. | **DONDE ACUDIR** | Unidad de Seguridad del campus. | **DOCUMENTOS** | Ninguno.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N2 - DTIC | **PRIORIDAD COBIT** | DSS02.04 | **ACCIONES DE MEJORA** | Programar mantenimiento preventivo de torniquetes',
        itil_category: 'Gestión de Incidentes',
        cobit_control: 'DSS02.04',
        cost_human: 60.0,
        cost_ia: 0.05,
      },
      {
        title: 'Cambio de datos personales en SIIU',
        description: 'Mi nombre está mal escrito en el sistema SIIU. Aparece "Luis" pero mi nombre correcto es "Luís". Ya fui a secretaría pero me dijeron que debía hacer un trámite en línea.',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Cambio de datos personales',
        tipo_solicitud: 'SOLICITUD_SERVICIO',
        priority: 'medio',
        urgency: 'medio',
        impact: 'bajo',
        status: 'ABIERTO',
        requester: 'Luís Fernández',
        tipo_usuario: 'ESTUDIANTE',
        facultad_o_area: 'Ciencias Exactas',
        carrera: 'Sistemas de la Información',
        ai_suggestion: '**PROCEDIMIENTO** | 1) Ingresar al SIIU. 2) Ir a Datos Personales. 3) Solicitar corrección. 4) Adjuntar documento de identidad. | **ESCALAMIENTO** | Si el sistema no permite la corrección, derivar a Secretaría General. | **REFERENCIA** | KB-SIIU-005',
        user_recommendation: '**QUE HACER** | Ingresa al SIIU, ve a Datos Personales y solicita la corrección. Adjunta una foto de tu cédula. | **DONDE ACUDIR** | Secretaría General si el sistema no lo permite. | **DOCUMENTOS** | Cédula de identidad.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N1 | **PRIORIDAD COBIT** | DSS02.01 | **ACCIONES DE MEJORA** | Verificar consistencia de datos',
        itil_category: 'Gestión de Solicitudes de Servicio',
        cobit_control: 'DSS02.01',
        cost_human: 10.0,
        cost_ia: 0.05,
      },
      {
        title: 'Beca Excelencia Académica - documento',
        description: 'Gané la Beca de Excelencia Académica pero no encuentro dónde firmar el contrato de beca. Me llegó un correo pero el enlace no funciona.',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Documentos para contrato de beca',
        tipo_solicitud: 'SOLICITUD_SERVICIO',
        priority: 'alto',
        urgency: 'alto',
        impact: 'medio',
        status: 'PENDIENTE_CLASIFICACION',
        requester: 'Diana Torres',
        tipo_usuario: 'ESTUDIANTE',
        facultad_o_area: 'Arquitectura',
        carrera: 'Arquitectura',
        ai_suggestion: '**PROCEDIMIENTO** | 1) Verificar enlace en correo institucional. 2) Contactar a Bienestar Estudiantil. 3) Firmar contrato digital. | **ESCALAMIENTO** | Contactar a la unidad de becas si el problema persiste. | **REFERENCIA** | KB-Becas-001',
        user_recommendation: '**QUE HACER** | Revisa tu correo institucional y haz clic en el enlace para firmar. Si no funciona, contacta a Bienestar Estudiantil. | **DONDE ACUDIR** | Unidad de Bienestar Estudiantil. | **DOCUMENTOS** | Cédula, comprobante de beca.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N1 | **PRIORIDAD COBIT** | DSS02.01 | **ACCIONES DE MEJORA** | Verificar enlaces en correos automáticos',
        itil_category: 'Gestión de Solicitudes de Servicio',
        cobit_control: 'DSS02.01',
        cost_human: 0,
        cost_ia: 0.05,
      },
      {
        title: 'Suficiencia Informática - no veo mi paralelo',
        description: 'Me matriculé en Suficiencia Informática pero en la plataforma no aparece mi paralelo. Ya pagé el valor correspondiente. Necesito saber en qué horario y aula me toca.',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Inconvenientes en visualización de paralelos',
        tipo_solicitud: 'INCIDENTE',
        priority: 'alto',
        urgency: 'urgente',
        impact: 'medio',
        status: 'ABIERTO',
        requester: 'Gabriel Herrera',
        tipo_usuario: 'ESTUDIANTE',
        facultad_o_area: 'Ciencias Exactas',
        carrera: 'Sistemas de la Información',
        ai_suggestion: '**PROCEDIMIENTO** | 1) Verificar matrícula en SIIU. 2) Revisar estado del pago. 3) Contactar a la unidad de suficiencia. | **ESCALAMIENTO** | Si el pago está confirmado y no aparece, escalar a la Coordinación de Suficiencia Informática. | **REFERENCIA** | KB-Suficiencia-001',
        user_recommendation: '**QUE HACER** | Verifica en SIIU que tu matrícula esté activa. Si pagaste y no aparece, contacta a la unidad de Suficiencia Informática. | **DONDE ACUDIR** | Unidad de Suficiencia Informática. | **DOCUMENTOS** | Comprobante de pago.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N1 -> N2 | **PRIORIDAD COBIT** | DSS02.03 | **ACCIONES DE MEJORA** | Revisar integración pagos-SIIU',
        itil_category: 'Gestión de Incidentes',
        cobit_control: 'DSS02.03',
        cost_human: 0,
        cost_ia: 0.05,
      },
      {
        title: 'Página web UCE no carga correctamente',
        description: 'La página web www.uce.edu.ec no carga correctamente en Firefox. Se ve en blanco. En Chrome funciona. Ya limpié caché pero sigue igual.',
        category: 'SOPORTE_DE_SISTEMAS_UCE',
        subcategoria: 'Inconvenientes al abrir la página',
        tipo_solicitud: 'INCIDENTE',
        priority: 'bajo',
        urgency: 'bajo',
        impact: 'bajo',
        status: 'RESUELTO',
        requester: 'Roberto Campos',
        tipo_usuario: 'ESTUDIANTE',
        facultad_o_area: 'Ciencias Exactas',
        carrera: 'Sistemas de la Información',
        ai_suggestion: '**PROCEDIMIENTO** | 1) Verificar compatibilidad del navegador. 2) Probar en Chrome/Edge. 3) Reportar incompatibilidad al equipo web. | **ESCALAMIENTO** | No requiere escalamiento, es un problema de navegador. | **REFERENCIA** | KB-Web-001',
        user_recommendation: '**QUE HACER** | Usa Chrome o Edge para acceder a la página. El problema es de compatibilidad con Firefox. | **DONDE ACUDIR** | No requiere. | **DOCUMENTOS** | Ninguno.',
        supervisor_suggestion: '**NIVEL DE ESCALAMIENTO** | N1 | **PRIORIDAD COBIT** | DSS02.03 | **ACCIONES DE MEJORA** | Revisar compatibilidad cross-browser',
        itil_category: 'Gestión de Incidentes',
        cobit_control: 'DSS02.03',
        resolution_time_minutes: 30,
        cost_human: 7.5,
        cost_ia: 0.05,
      },
    ];

    for (const ticket of tickets) {
      const created = await this.prisma.ticket.create({
        data: {
          ...ticket,
          feedback_ia: null,
        },
      });

      await this.prisma.auditLog.create({
        data: {
          ticket_id: created.id,
          action: 'CREACION',
          details: JSON.stringify({ seed: true, categoria: ticket.category }),
        },
      });

      this.logger.log(`Ticket creado: ${created.id.slice(0, 8)}... - ${ticket.title}`);
    }

    this.logger.log(`Seed completado: ${tickets.length} tickets creados.`);
  }
}
